services:

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123

  gateway:
    build: ../api-gateway
    ports:
      - "8080:8080"

  auth-service:
    build: ../services/auth-service
    ports:
      - "3001:3000"

  document-service:
    build: ../services/document-service

  classification-service:
    build: ../services/classification-service